"""Configuration management for local-deepwiki.

This package provides Pydantic-based configuration models and loading utilities.
Split into multiple modules for maintainability while preserving backward compatibility.
"""

# Re-export all public names for backward compatibility
from local_deepwiki.config.loader import (
    ConfigChange,
    ConfigDiff,
    config_context,
    get_config,
    load_config_from_env,
    merge_configs,
    reset_config,
    set_config,
    validate_config,
)
from local_deepwiki.config.models import (
    RESEARCH_DECOMPOSITION_PROMPTS,
    RESEARCH_GAP_ANALYSIS_PROMPTS,
    RESEARCH_PRESETS,
    RESEARCH_SYNTHESIS_PROMPTS,
    WIKI_SYSTEM_PROMPTS,
    AnthropicConfig,
    ASTCacheConfig,
    ChunkingConfig,
    Config,
    DeepResearchConfig,
    EmbeddingBatchConfig,
    EmbeddingCacheConfig,
    EmbeddingConfig,
    ExportBatchConfig,
    FuzzySearchConfig,
    HooksConfig,
    LazyIndexConfig,
    LLMCacheConfig,
    LLMConfig,
    LocalEmbeddingConfig,
    OllamaConfig,
    OpenAIEmbeddingConfig,
    OpenAILLMConfig,
    OutputConfig,
    ParsingConfig,
    PluginsConfig,
    PromptsConfig,
    ProviderPromptsConfig,
    ResearchPreset,
    SearchCacheConfig,
    SearchConfig,
    WikiConfig,
)

__all__ = [
    # Models
    "Config",
    "ResearchPreset",
    "RESEARCH_PRESETS",
    "RESEARCH_DECOMPOSITION_PROMPTS",
    "RESEARCH_GAP_ANALYSIS_PROMPTS",
    "RESEARCH_SYNTHESIS_PROMPTS",
    "WIKI_SYSTEM_PROMPTS",
    "LocalEmbeddingConfig",
    "OpenAIEmbeddingConfig",
    "EmbeddingConfig",
    "OllamaConfig",
    "AnthropicConfig",
    "OpenAILLMConfig",
    "LLMConfig",
    "ParsingConfig",
    "EmbeddingBatchConfig",
    "ASTCacheConfig",
    "ChunkingConfig",
    "WikiConfig",
    "DeepResearchConfig",
    "PluginsConfig",
    "HooksConfig",
    "ExportBatchConfig",
    "OutputConfig",
    "EmbeddingCacheConfig",
    "LLMCacheConfig",
    "SearchCacheConfig",
    "SearchConfig",
    "LazyIndexConfig",
    "FuzzySearchConfig",
    "ProviderPromptsConfig",
    "PromptsConfig",
    # Loader functions
    "get_config",
    "set_config",
    "reset_config",
    "config_context",
    "ConfigChange",
    "ConfigDiff",
    "merge_configs",
    "validate_config",
    "load_config_from_env",
]
